// <auto-generated />
using System;
using AgizDisSagligi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgizDisSagligi.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808164546_NotGorselYoluNullable")]
    partial class NotGorselYoluNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgizDisSagligi.Entities.DurumKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HedefId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("time");

                    b.Property<int>("Sure")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Uygulandi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HedefId");

                    b.ToTable("DurumKayitlari");
                });

            modelBuilder.Entity("AgizDisSagligi.Entities.Hedef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("OnemDerecesi")
                        .HasColumnType("int");

                    b.Property<int>("PeriyotSiklik")
                        .HasColumnType("int");

                    b.Property<string>("PeriyotZaman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Hedefler");
                });

            modelBuilder.Entity("AgizDisSagligi.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParolaSifreli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("AgizDisSagligi.Entities.Not", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GorselYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Notlar");
                });

            modelBuilder.Entity("AgizDisSagligi.Entities.Oneri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Oneriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Metin = "Dişlerinizi günde en az iki kez, 2 dakika süreyle fırçalayın."
                        },
                        new
                        {
                            Id = 2,
                            Metin = "Diş ipini her gün kullanmayı unutmayın."
                        },
                        new
                        {
                            Id = 3,
                            Metin = "Fırçanızı her 3 ayda bir değiştirin."
                        },
                        new
                        {
                            Id = 4,
                            Metin = "Şekerli ve asitli içeceklerin tüketimini azaltın."
                        },
                        new
                        {
                            Id = 5,
                            Metin = "Yılda en az bir kez diş hekimi kontrolüne gidin."
                        },
                        new
                        {
                            Id = 6,
                            Metin = "Fırçalamadan sonra ağız gargarası kullanmayı düşünün."
                        },
                        new
                        {
                            Id = 7,
                            Metin = "Sert kıllı yerine yumuşak kıllı diş fırçası tercih edin."
                        });
                });

            modelBuilder.Entity("AgizDisSagligi.Entities.DurumKaydi", b =>
                {
                    b.HasOne("AgizDisSagligi.Entities.Hedef", "Hedef")
                        .WithMany("DurumKayitlari")
                        .HasForeignKey("HedefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hedef");
                });

            modelBuilder.Entity("AgizDisSagligi.Entities.Hedef", b =>
                {
                    b.HasOne("AgizDisSagligi.Entities.Kullanici", "Kullanici")
                        .WithMany("Hedefler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("AgizDisSagligi.Entities.Not", b =>
                {
                    b.HasOne("AgizDisSagligi.Entities.Kullanici", "Kullanici")
                        .WithMany("Notlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("AgizDisSagligi.Entities.Hedef", b =>
                {
                    b.Navigation("DurumKayitlari");
                });

            modelBuilder.Entity("AgizDisSagligi.Entities.Kullanici", b =>
                {
                    b.Navigation("Hedefler");

                    b.Navigation("Notlar");
                });
#pragma warning restore 612, 618
        }
    }
}
